server:
  port: 8860
spring:
  application:
    name: "gateway"

# https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html
zuul:
  ignored-services: '*'
  routes:
    grettings:
      path: /message/**
      service-id: greetings